# Config file for automatic testing at travis-ci.org

language: python

matrix:
  include:
    - python: 3.6
      dist: trusty
      sudo: false
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8
      dist: xenial
      sudo: true

install:
  - pip install clipboard
  - pip install colorama
  - pip install coveralls

script:
  - coverage run sudosol/sudosol.py --batch tests/tests.batch

after_success:
  - coveralls
